### ISSUE TITLE
NZ Hack House

### ISSUE THREAD

**Issue by lstoll** [lstoll/travel#35]
Spend a week in NZ, working from a really nice place. Thinking [Dry Olive](http://www.dryolivehomestay.com). Looking at the calendar, some time in the last 2 weeks of Feb look the Best. This could be scheduled after Webstock, and hopefully around a Railscamp NZ. Probably should book soon though.

Interested?

TRAMOPOLINE

![2013-09-30 at 1 21 pm](https://f.cloud.github.com/assets/694/1236501/5d658910-29c2-11e3-80c5-beb65666de0d.png)

/cc @dgoodlad @benburkert @benschwarz @rodjek #33

**Comment by benschwarz** [comment]
Interested.

**Comment by dgoodlad** [comment]
:+1: let's make it happen

**Comment by bgentry** [comment]
[![](https://i1.ytimg.com/vi/Zh5knx1Bt64/sddefault.jpg)](https://www.youtube.com/watch?v=Zh5knx1Bt64)

tramampoline!

**Comment by bgentry** [comment]
Dry Olive was amazing. Would love to stay there again, longer this time!

**Comment by lstoll** [comment]
Would be looking at a full week there. Trying to work out what the deal is with railscamp NZ.

**Comment by lstoll** [comment]
![2013-10-02 at 3 31 pm](https://f.cloud.github.com/assets/694/1256645/4f2427e8-2b99-11e3-99c4-f44cd3105788.png)

So the railscamp NZ is at the location we want, but later than expected (7-10 Mar). Who'd be interested in going to that? Should we align this with that Railscamp?

also /cc @wfarr

**Comment by benschwarz** [comment]
I won't go to that—

**Comment by dgoodlad** [comment]
So, this is happening! @MissG suggested we might want to get a people-mover of some description for wine adventures. Thoughts?

**Comment by MissG** [comment]
Ahoy there campers,

So I'm going through and booking everything for Dave and I at the moment and have a few things that I wanted to confirm group-wise, as they affect other parts of our travel.
1. How many cars do we want between the lot of us? It makes sense if people are coming up from Christchurch that we do a consolidation of cars there (and potentially transfer to a really sexy people mover), then roadtrip the last 4 glorious hours together.
   ![](http://www.apexrentals.co.nz/graphics/brag_mpv.jpg)
2. What are people's plans on the last day of Hack House? I will be flying from Christchurch up to Auckland on that day and am trying to figure out best times to book... with a 4 hour drive beforehand, so I'm thinking afternoon. Does this work with the rail scamp adventures? What are the lovely ladies plans?
3. Also booking Dave's flight from Christchurch to Auckland after rail scamp... can you lot come up with a time you'd be arriving at Christchurch Airport so that we can plan appropriate timing for flights? I hear it's a 2 hour drive from Mt Cheesy to the airport.

Many loves,
G

**Comment by lstoll** [comment]
So far it's 4 os us, which would fit in a car.

We'll be coming up the other coast, so only potential drop off spot is Blenheim or Picton. Did you see how much a people mover cost?

On the last (Fri) day @codenamejac will be flying out from Christchurch to Melbourne at 1600 I think - So would probably want to get to CHC airport by 1400 at the latest. From there, drive to the Railscamp in one car, which we can return when @dgoodlad / I fly out (16h mon for me).

I guess the group car etc. depends on if @benschwarz or @alanjrogers or @rodjek or whatever come on down. If we end up a house full of GitHub people, I'll consider looking at making it an 'official' stay, if we work on something.

**Comment by MissG** [comment]
Righto.

So I'm going to book a flight out of CHC at 3pm to Auckland for myself on the 7th. I'm also going to look at booking a car for Dave and I from Queenstown to Blenheim. Keep in mind that 4 people with luggage is pretty tight in a sedan - particularly as Dave and I will be travelling with our lives on our backs.

Group car from Blenheim to Christchuch Airport - a people mover is $109 per day through Apex, which compares to about $64 per day for a standard sedan. The big benefit comes with reducing number of designated drivers should we go out for dinner / to wineries.

@benschwarz @alanjrogers @rodjek - any interest/vote on a group car?

**Comment by lstoll** [comment]
Sorry about the delays, still on the radar - just need to work out who exactly is there first.

A van probably makes sense, we'll just need to co-ordinate dropping off other rental cars in blenheim, then switching back to a car in chc.

**Comment by MissG** [comment]
Sweet. I have booked a car for drop off at Blenheim at 4pm on that day (although I'm sure if we rocked up earlier it wouldn't be an issue). Can book a van for $129 per day from Blenheim to Christchurch - let me know and I can book it in.

PS we are booking through Apex Rentals.

**Comment by benschwarz** [comment]
Thanks for the reminder. I'll get my shit together (write it on the fridge) and see if I can figure out what we're up to.
