### ISSUE TITLE
Go to Tresor Wednesday night

### ISSUE THREAD

**Issue by rsanheim** [lstoll/travel#9]
A bunch of hubbers will be at Tresor Wednesday night for the beats.  You should join.  I imagine we will do drinks somewheres before and get there around 1230 ish.

/cc @dylanegan @roidrage

**Comment by lstoll** [comment]
Are you going straight from the club to the airport? Madness! Had a big night last night, will ping you all later on.

**Comment by rsanheim** [comment]
...the things I do for techno...

**Comment by dylanegan** [comment]
@rsanheim I'm hitting up some jazz, but I might be keen on getting my :fist: :wave: going.

**Comment by rsanheim** [comment]
@lstoll or @dylanegan do you have a recommendation for some place chill to have drinks in Friedrichshain before Tresor?

**Comment by dylanegan** [comment]
@rsanheim I do not, but http://www.b-flat-berlin.de/index.php?lang=en&to=programm&vorschau=0 is where we're going for some jazz. Free on Wednesdays. @durran might know.

**Comment by durran** [comment]
@rsanheim The bar I liked the most in F'hain closed a while back so I don't really know. (I spend most my nights in Kreuzberg.)

But here are some recommendations for Kreuzberg anyways, since Tresor is there and everything is easy to get to from the U1 hot spot stations (Kotti, Görli, Schlesi, Warschauer).

[Barbie Deinhoff's](http://barbiedeinhoff.de/) (Schlesisches Tor) (Tiny with good electro vibe)
[Madame Claude](http://www.facebook.com/MadameClaudeBerlin) (Schlesisches Tor) (Furniture is on the ceiling, wide array of experimental music)

[Wiener Blut](http://de-de.facebook.com/wienerblut36) (Görlitzer Banhof) (Mostly rock/punk music and crowd - this is my local)

[Würgeengel](http://www.wuergeengel.de/de/index.html) (Kottbusser Tor) (Nice cocktail bar hidden in the back alley behind the station)

If you're not opposed to venturing a little further, like Prenzlauer Berg or Schöneberg there are some really killer cocktail bars:

[Beckett's Kopf](http://www.becketts-kopf.de/) (Eberswalder Str.) (In my opinion the best made cocktails in Berlin, but you will wait for them.) :)

[Green Door](http://greendoor.de/) (Nollendorfplatz) (The best cocktail bar in Berlin, all around. Be prepared to be completely wasted after a few drinks... Also if you go tell them I sent you as it's my second local... :))
[Stagger Lee](http://www.staggerlee.de/) (Nollendorfplatz) (Another great cocktail bar that is decorated like an old west saloon)

**Comment by dylanegan** [comment]
I think @sr totally won at Tresor. Need to get in to Berghain.

**Comment by rsanheim** [comment]
Haven't showered in so long.  Winning at air travel.

Sent from phonetron 9000

On Jul 12, 2012, at 6:20, Dylan Egan notifications@github.com wrote:

I think @sr https://github.com/sr totally won at Tresor. Need to get in
to Berghain.

—
Reply to this email directly or view it on
GitHubhttps://github.com/lstoll/travel/issues/9#issuecomment-6931672
.

**Comment by sr** [comment]
Winning at train travel over here. Wins everywhere.
